# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a91a649a3e1718dc093430ca489ddceaa98d71f5486ad648c0af9e77254718a2c93c7566fc5b7f21efefc08045c12d9fb2526351724b4ac4e9dfb74d7b570e8

test:
  secret_key_base: 91835c2cbaa1a0ba2e1bc9594e223deba06be0a5cbdad29188dcb18d3ba0f5655f6b35dad7bd472ca6e5832cbfca4a452d1a41a3c503e7bc0cf55c3fbe648545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
